version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "certifications-audios"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xnf6gs5etvw4"
s3_prefix = "certifications-audios"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
